---
- name: Management Host Objects
  ansible.builtin.import_tasks: host_mgmt_objects.yml
- name: Mgmt Network Objects
  ansible.builtin.import_tasks: net_objects.yml
- name: DMZ Web Server
  ansible.builtin.import_tasks: dmz.yml
