$ANSIBLE_VAULT;1.1;AES256
37316238393531626234666162343131666334323036373261613364373834373236396535356430
6636343333656264316331366565313836353233626635340a663333316136386331316263326462
33666234613534656339663530366634303635326534363339646264303065623863356266306439
3531373065383034320a346139343664353365336138396636373239373633333965636431313364
62356239636337393833393530643737626465336334346438356333656562356538356365313333
62363238653866633061386331393634306662646231373465353634336337356265626561666236
33396335636437626232313635313637636564306461623363346432616163633664623062393961
33306537646538326336376464623432363136386532666631643964323638636438663134373338
3165
