---
fw_policy_base_position: 1
fw_policy_mgmt_rules:
  - name: "Ansible Management Access"
    source:
      - Ansible Server
      - Windows SmartConsole
      - Windows SmartConsole Public
    destination:
      - "{{ fw_name }}"
    service: Any
    action: "Accept"
    position: "{{ fw_policy_base_position }}"

  - name: "SSH Access"
    source: Any
    destination:
      - "{{ fw_name }}"
    service: SSH
    action: "Accept"
    position: "{{ fw_policy_base_position + 1 }}"

fw_policy_dmz_rules:
  - name: "Corp Web Server Access"
    source: Any
    destination:
      - Corp Web Server
    service:
      - http
      - https
    action: "Accept"
    position: "{{ fw_policy_base_position + 2 }}"
